full:
	flex lexer.l && clang main.c -o main && ./main 1
	flex lexer.l && clang main.c -o main && ./main 2
	flex lexer.l && clang main.c -o main && ./main 3
	flex lexer.l && clang main.c -o main && ./main 4
	flex lexer.l && clang main.c -o main && ./main 5
	flex lexer.l && clang main.c -o main && ./main 6
	flex lexer.l && clang main.c -o main && ./main 7
	
1:
	flex lexer.l && clang main.c -o main && ./main 1	
2:
	flex lexer.l && clang main.c -o main && ./main 2
3:
	flex lexer.l && clang main.c -o main && ./main 3
4:
	flex lexer.l && clang main.c -o main && ./main 4
5:
	flex lexer.l && clang main.c -o main && ./main 5
6:
	flex lexer.l && clang main.c -o main && ./main 6
7:
	flex lexer.l && clang main.c -o main && ./main 7